WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Елена\PycharmProjects\pythonProject21\module12_4.py", line 71, in test_run
    runner2 = Runner(100, 8)
              ^^^^^^^^^^^^^^
  File "C:\Users\Елена\PycharmProjects\pythonProject21\module12_4.py", line 9, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Елена\PycharmProjects\pythonProject21\module12_4.py", line 64, in test_walk
    runner1 = Runner("TestRunner", -7)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Елена\PycharmProjects\pythonProject21\module12_4.py", line 14, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -7
